[package]
name = "countdown"
version = "0.1.0"
authors = ["james"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "countdown_benchmark"
harness = false

[dependencies]
